#language models
SIMILARITY_MODEL= "lsi_model_wiki_cancer_54037x300"
SIMILARITY_MODULE = "similarity"
#speech service
CLOUDSPEECH = "speech/cloudspeech.json"
#content
TRAINING_FILE = "domains/mohamed_video1.json"
#modules
SPEECH_INTERFACE = 'speech_system'
DIALOGUE_MANAGER = 'dialogue_manager'
INFORMATION_STATE='information_state'
GOAL_MANAGER='goal_manager'
RULES_MANAGER='rules'
NLU='nlu'
NLG='nlg'
#logs
TUTORING_LOG='tutoring.log'
#thresholds
##### goal
NUM_ATTEMPTS_THRESHOLD='2'
SIMILARITY_THRESHOLD='0.80'
#flags
BYPASS_SENTENCE_COMPLETION = 'False'
# policies
##### goal
ACTION_FOR_INCOMPLETE_ANSWERS = 'table'